name: Go

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "v*"          # prevent infinite loops when pushing tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: write   # required for tags + GitHub releases
      packages: write   # required for GHCR push

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for tag calculation

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libvirt-dev   qemu-kvm  libvirt-daemon-system  libvirt-clients  bridge-utils  virtinst wget libguestfs-tools passt
          sudo systemctl enable --now libvirtd
          sudo systemctl start libvirtd

      - name: WGET
        run: wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

      - name:  Resize
        run: qemu-img resize noble-server-cloudimg-amd64.img +20G

      - name:  Extend cloud image
        env:
          LIBGUESTFS_MEMSIZE: "512"
          #          LIBGUESTFS_BACKEND: direct
            #          LIBGUESTFS_NETWORK: "1"
            #          LIBGUESTFS_USE_PASST: "0"
        run: sudo virt-customize -v  -a noble-server-cloudimg-amd64.img --install ubuntu-desktop
