name: Go

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "v*"          # prevent infinite loops when pushing tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04 ## Only works on ubuntu 22.04 

    permissions:
      contents: write   # required for tags + GitHub releases
      packages: write   # required for GHCR push

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for tag calculation

      - name: Install packages
        run: |
          sudo apt update -y
          sudo apt install wget curl libguestfs-tools -y

      - name: WGET
        run: wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

      - name:  Resize
        run: |
          qemu-img create -f qcow2 noble-expanded.img 8G
          sudo virt-resize --expand /dev/sda1 noble-server-cloudimg-amd64.img noble-expanded.img

      - name:  Extend cloud image
        run: |
          sudo virt-customize -v -a noble-expanded.img \
            --install xfce4,xfce4-goodies,xfce4-terminal,lightdm,lightdm-gtk-greeter,xauth,xserver-xorg-input-libinput,xserver-xorg-legacy,xrdp,xorgxrdp,dbus-x11,grub-pc-bin,vim,net-tools,nmap,snapd \
            --run-command 'ln -sf /dev/null /etc/systemd/system/systemd-networkd-wait-online.service' \
            --upload google-chrome-stable_current_amd64.deb:/tmp/google-chrome-stable_current_amd64.deb \
            --run-command 'grub-install --target=i386-pc /dev/sda' \
            --run-command 'update-grub' \
            --run-command 'apt-get clean && rm -rf /var/lib/apt/lists/*'
          ls -la

      - name:  Compress cloud image
        run: |
          sudo virt-sparsify --compress noble-expanded.img noble-desktop-cloudimg-amd64.img
          ls -la

      # -------------------------------
      # Versioning & Release (main only)
      # -------------------------------
      - name: Bump version and create tag
        if: github.event_name == 'push'
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main

      - name: Create GitHub release
        if: github.event_name == 'push' && steps.tag.outputs.new_tag != ''
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
          artifacts: noble-desktop-cloudimg-amd64.img
