name: Go

on:
  push:
    branches: [ "main" ]
    tags-ignore:
      - "v*"          # prevent infinite loops when pushing tags
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write   # required for tags + GitHub releases
      packages: write   # required for GHCR push

    steps:
      # -------------------------------
      # Checkout
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # REQUIRED for tag calculation

      - name: Install packages
        run: |
          sudo apt update -y
          sudo apt install wget curl libguestfs-tools -y

      - name: WGET
        run: wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img

      - name:  Resize
        run: |
          qemu-img create -f qcow2 noble-expanded.img 8G
          ls -la
          sudo virt-resize --expand /dev/sda1 noble-server-cloudimg-amd64.img noble-expanded.img
          ls -la
          df -h

      - name:  Extend cloud image
        run: |
          sudo  virt-customize -v  -a noble-expanded.img --install ubuntu-desktop-minimal,xrdp --run-command 'apt-get clean && rm -rf /var/lib/apt/lists/*'
          ls -la
          df -h

      - name:  Compress cloud image
        run: |
          sudo virt-sparsify --compress noble-expanded.img noble-final.img
          ls -la
          df -h


